root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o ./bin/main ./cmd/api"
  bin = "bin/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "bin", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  delay = 1000

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true